#!/bin/bash -e

BLUE='\E[1;34m'
CYAN='\E[1;36m'
YELLOW='\E[1;33m'
GREEN='\E[1;32m'
RESET='\E[0m'

echo -e "${BLUE}❯ ${CYAN}Building libmodsecurity ${YELLOW}${LIBMODSECURITY_VERSION} ...${RESET}"

cd /tmp
git clone --recursive --branch v${LIBMODSECURITY_VERSION} https://github.com/owasp-modsecurity/ModSecurity modsecurity
cd /tmp/modsecurity

./build.sh
./configure

make -j$(nproc)
make install

echo -e "${BLUE}❯ ${GREEN}libmodsecurity build completed${RESET}"
