#!/bin/bash -e

BLUE='\E[1;34m'
CYAN='\E[1;36m'
YELLOW='\E[1;33m'
GREEN='\E[1;32m'
RESET='\E[0m'

echo -e "${BLUE}❯ ${CYAN}Building OpenResty ${YELLOW}${OPENRESTY_VERSION} ${CYAN}with ModSecurity-nginx ${YELLOW}${MODSECURITY_NGINX_VERSION}...${RESET}"

cd /tmp
# HTTP GeoIP2 module
echo -e "${BLUE}❯ ${CYAN}Downloading HTTP GeoIP2 module ${YELLOW}${NGINX_HTTP_GEOIP2_MODULE_VERSION}...${RESET}"
mkdir ngx_http_geoip2_module
curl -# -L "${NGINX_HTTP_GEOIP2_MODULE_URL}" | tar xz --strip 1 -C ngx_http_geoip2_module
# MaxMind DB
echo -e "${BLUE}❯ ${CYAN}Downloading maxmind_db...${RESET}"
mkdir libmaxminddb
curl -# -L "${LIBMAXMINDDB_URL}" | tar xz --strip 1 -C libmaxminddb
echo -e "${BLUE}❯ ${CYAN}Configuring lib-maxmind_db ${YELLOW}${MAXMINDDB_VERSION}...${RESET}"
cd libmaxminddb
./configure \
    --prefix=/usr \
    --mandir=/tmp/libmaxminddb-man \
    --with-pic \
    --enable-shared=yes \
    --enable-static=yes
make
make check
make install
ldconfig

cd ..

# modsecurity
mkdir /tmp/modsecurity-nginx
curl -# -L  "${MODSECURITY_NGINX_URL}" | tar -xz --strip 1 -C /tmp/modsecurity-nginx

# OpenResty
mkdir openresty
curl -# -L "${OPENRESTY_URL}" | tar xz --strip 1 -C openresty
cd /tmp/openresty
./configure \
        --prefix=/etc/nginx \
        --sbin-path=/usr/sbin/nginx \
        \
        --modules-path=/usr/lib/nginx/modules \
        --conf-path=/etc/nginx/nginx.conf \
        --pid-path=/var/run/nginx.pid \
        --lock-path=/var/run/nginx.lock \
        \
        --http-client-body-temp-path=/var/cache/nginx/client_temp \
        --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
        --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
        --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
        --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
        --with-perl_modules_path=/usr/lib/perl5/vendor_perl \
        \
        --add-module=/tmp/ngx_http_geoip2_module \
        --user=nginx \
        --group=nginx \
        --with-compat \
        --with-debug \
        --with-threads \
        --with-file-aio \
        --with-pcre-jit \
        \
        --with-http_addition_module \
        --with-http_addition_module \
        --with-http_auth_request_module \
        --with-http_dav_module \
        --with-http_flv_module \
        --with-http_gunzip_module \
        --with-http_gzip_static_module \
        --with-http_mp4_module \
        --with-http_random_index_module \
        --with-http_realip_module \
        --with-http_secure_link_module \
        --with-http_auth_request_module \
        --with-http_degradation_module \
        --with-http_slice_module \
        --with-http_ssl_module \
        --with-http_stub_status_module \
        --with-http_sub_module \
        --with-http_v2_module \
        \
        --with-mail \
        --with-mail_ssl_module \
        \
        --with-stream \
        --with-stream_realip_module \
        --with-stream_ssl_module \
        --with-stream_ssl_preread_module \
	      --add-module=/tmp/modsecurity-nginx

make -j2

echo -e "${BLUE}❯ ${GREEN}OpenResty build completed${RESET}"