#!/bin/bash -e

BLUE='\E[1;34m'
CYAN='\E[1;36m'
YELLOW='\E[1;33m'
GREEN='\E[1;32m'
RESET='\E[0m'

echo -e "${BLUE}❯ ${CYAN}Building libmaxminddb ${YELLOW}${MAXMIND_VERSION}...${RESET}"

cd /tmp
wget "https://github.com/maxmind/libmaxminddb/releases/download/${MAXMIND_VERSION}/libmaxminddb-${MAXMIND_VERSION}.tar.gz"
tar -xzf libmaxminddb-${MAXMIND_VERSION}.tar.gz
mv /tmp/libmaxminddb-${MAXMIND_VERSION} /tmp/libmaxminddb
cd /tmp/libmaxminddb

./configure
make
make check
#Needs to be installed in order to build modsecurity, will be installed again in the final image
make install
ldconfig

echo -e "${BLUE}❯ ${GREEN}libmaxminddb build completed${RESET}"
