#!/bin/bash -e

BLUE='\E[1;34m'
CYAN='\E[1;36m'
YELLOW='\E[1;33m'
GREEN='\E[1;32m'
RESET='\E[0m'


# Install CrowdSec OpenResty Bouncer.
cd /tmp
# Download the CrowdSec OpenResty Bouncer package.
echo -e "${BLUE}❯ ${CYAN}Downloading CrowdSec Openresty Bouncer package ${YELLOW}${CROWDSEC_OPENRESTY_BOUNCER_VERSION}...${RESET}"
mkdir crowdsec-openresty-bouncer
curl -# -L "${CROWDSEC_OPENRESTY_BOUNCER_URL}" | tar xz --strip 1 -C crowdsec-openresty-bouncer

echo -e "${BLUE}❯ ${GREEN}CrowdSec OpenResty-Bouncer download completed${RESET}"
