#!/bin/bash -e

BLUE='\E[1;34m'
CYAN='\E[1;36m'
YELLOW='\E[1;33m'
GREEN='\E[1;32m'
RESET='\E[0m'

echo -e "${BLUE}❯ ${CYAN}Building docker multi-arch: ${YELLOW}${*}${RESET}"

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${DIR}/.."

# Buildx Builder
docker buildx create --name "${BUILDX_NAME:-nginx-full}" || echo
docker buildx use "${BUILDX_NAME:-nginx-full}"

docker buildx build \
	--platform linux/amd64,linux/arm64,linux/arm/7 \
	--progress plain \
	--pull \
	--build-arg BASE_TAG \
	--build-arg ACMESH_BASE_TAG \
	--build-arg CERTBOT_BASE_TAG \
	--build-arg OPENRESTY_VERSION \
	--build-arg LUA_VERSION \
	--build-arg LUAROCKS_VERSION \
	--build-arg NGINX_HTTP_GEOIP2_MODULE_VERSION \
  --build-arg MAXMINDDB_VERSION \
  --build-arg CROWDSEC_OPENRESTY_BOUNCER_VERSION \
  --build-arg MODSECURITY_VERSION \
  --build-arg MODSECURITY_NGINX_VERSION \
	"$@" \
	.

docker buildx rm "${BUILDX_NAME:-nginx-full}"

echo -e "${BLUE}❯ ${GREEN}Multi-arch build Complete${RESET}"
