#!/bin/bash -e

BLUE='\E[1;34m'
CYAN='\E[1;36m'
YELLOW='\E[1;33m'
GREEN='\E[1;32m'
RESET='\E[0m'

echo -e "${BLUE}❯ ${CYAN}Building ModSecurity ${YELLOW}${MODSECURITY_VERSION}...${RESET}"

cd /tmp
git clone --depth 1 --branch v${MODSECURITY_VERSION} https://github.com/SpiderLabs/ModSecurity.git modsecurity
cd /tmp/modsecurity

./build.sh

git submodule init
git submodule update

./configure \
    --with-lmdb \
    --enable-parser-generation \
    --enable-mutex-on-pm
make
#Installing it directly makes up for a smaller layer in the docker history, there is over 1GB of .o files
make install

echo -e "${BLUE}❯ ${GREEN}ModSecurity build completed${RESET}"
