#!/bin/bash -e



echo -e "${BLUE}❯ ${CYAN}Downloading CrowdSec Openresty Bouncer package ${YELLOW}${CROWDSEC_OPENRESTY_BOUNCER_VERSION}...${RESET}"
mkdir -p /crowdsec/
cd /tmp
mkdir -p crowdsec-openresty-bouncer
curl -# -L ${CROWDSEC_OPENRESTY_BOUNCER_URL} | tar xz --strip 1 -C crowdsec-openresty-bouncer
echo -e "${BLUE}❯ ${CYAN}Installing CrowdSec OpenResty-Bouncer ${YELLOW}${CROWDSEC_OPENRESTY_BOUNCER_VERSION}...${RESET}"
cp /tmp/crowdsec-openresty-bouncer/openresty/crowdsec_openresty.conf /crowdsec/crowdsec_openresty.conf
sed-patch 's|/etc/crowdsec/bouncers/crowdsec-openresty-bouncer.conf|/data/crowdsec/crowdsec-openresty-bouncer.conf|' /crowdsec/crowdsec_openresty.conf
#sed-patch 's|/usr/local/openresty/lualib/plugins/crowdsec|/etc/nginx/lualib/plugins/crowdsec|' /crowdsec/crowdsec_openresty.conf
sed-patch 's|$prefix/../lualib/plugins/crowdsec|/etc/nginx/lualib/plugins/crowdsec|' /crowdsec/crowdsec_openresty.conf
echo -e "${BLUE}❯ ${CYAN}Patched crowdsec_openresty.conf"
echo -e "${BLUE}❯ ${CYAN}Grabbing bouncer config template using curl"
#cp /tmp/crowdsec-openresty-bouncer/config/template.conf /crowdsec/crowdsec-openresty-bouncer.conf
curl -H 'Accept: application/vnd.github.v3.raw' \
  -o /crowdsec/crowdsec-openresty-bouncer.conf.template \
  -L https://raw.githubusercontent.com/crowdsecurity/lua-cs-bouncer/main/config_example.conf
cp -r /tmp/crowdsec-openresty-bouncer/lua /crowdsec/
echo -e "${BLUE}❯ ${GREEN}CrowdSec OpenResty-Bouncer install completed${RESET}"
