#!/bin/bash -e

BLUE='\E[1;34m'
CYAN='\E[1;36m'
YELLOW='\E[1;33m'
GREEN='\E[1;32m'
RESET='\E[0m'

echo -e "${BLUE}❯ ${CYAN}Installing libmaxminddb ${YELLOW}${MAXMIND_VERSION}...${RESET}"

cd /tmp/libmaxminddb
make install
ldconfig
rm -rf /tmp/libmaxminddb

echo -e "${BLUE}❯ ${GREEN}libmaxminddb install completed${RESET}"