#!/bin/bash -e

BLUE='\E[1;34m'
CYAN='\E[1;36m'
YELLOW='\E[1;33m'
GREEN='\E[1;32m'
RESET='\E[0m'


echo -e "${BLUE}❯ ${CYAN}Installing MaxMind DB ${YELLOW}${MAXMINDDB_VERSION}...${RESET}"
cd /tmp/libmaxminddb
make install
ldconfig
echo -e "${BLUE}❯ ${GREEN}MaxMind DB install completed${RESET}"

echo -e "${BLUE}❯ ${CYAN}Installing ModSecurity ${YELLOW}${MODSECURITY_VERSION}...${RESET}"
# pre-built modsecurity is already copied into /usr/local/modsecurity
mkdir -p /usr/local/modsecurity/templates/ruleset

cp /tmp/configs/modsecurity.conf /usr/local/modsecurity/templates/modsecurity.conf
cp /tmp/configs/unicode.mapping /usr/local/modsecurity/templates/unicode.mapping

sed-patch 's|SecRuleEngine.*|SecRuleEngine On|' /usr/local/modsecurity/templates/modsecurity.conf
sed-patch 's|SecAuditLog.*|SecAuditLog /data/logs/modsec_audit.log|' /usr/local/modsecurity/templates/modsecurity.conf
echo -e "${BLUE}❯ ${GREEN}ModSecurity install completed${RESET}"

cat <<EOF > /usr/local/modsecurity/templates/main.conf
Include /etc/nginx/modsec/modsecurity.conf
Include /etc/nginx/modsec/ruleset/crs-setup.conf
Include /etc/nginx/modsec/ruleset/rules/*.conf
EOF

echo -e "${BLUE}❯ ${CYAN}Installing OWASP-CoreRuleSet ${YELLOW}${CRS_VERSION}...${RESET}"
curl -# -L "https://codeload.github.com/coreruleset/coreruleset/tar.gz/refs/tags/v${CRS_VERSION}" | tar xz --strip 1 -C /usr/local/modsecurity/templates/ruleset
mv /usr/local/modsecurity/templates/ruleset/crs-setup.conf.example /usr/local/modsecurity/templates/ruleset/crs-setup.conf
mv /usr/local/modsecurity/templates/ruleset/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf.example /usr/local/modsecurity/templates/ruleset/rules/REQUEST-900-EXCLUSION-RULES-BEFORE-CRS.conf
echo -e "${BLUE}❯ ${GREEN}OWASP-CoreRuleSet install completed${RESET}"
