#!/bin/bash -e

echo -e "${BLUE}❯ ${CYAN}Installing OpenResty ${YELLOW}${OPENRESTY_VERSION}...${RESET}"
cd /tmp/openresty
make install
echo -e "${BLUE}❯ ${GREEN}OpenResty install completed${RESET}"

echo -e "${BLUE}❯ ${CYAN}Installing OpenResty plugins...${RESET}"
luarocks install lua-cjson
luarocks install lua-resty-openidc
# Crowdsec needs lua-resty-http, since this method does not use the install.sh script supplied with the bouncer
luarocks install lua-resty-http
echo -e "${BLUE}❯ ${GREEN}OpenResty plugins install completed${RESET}"
