#!/bin/bash -e

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${DIR}/.."

export IMAGE=nginx-full
export BASE_TAG=latest
export OPENRESTY_VERSION=1.19.3.1
export LUA_VERSION=5.1.5
export LUAROCKS_VERSION=3.3.1
export OPENSSL_VERSION=1.1.1t

#./scripts/buildx --push -f docker/Dockerfile -t docker.io/nginxproxymanager/${IMAGE}:${BASE_TAG}
./scripts/buildx --push -f docker/Dockerfile -t docker.io/nginxproxymanager/${IMAGE}:latest
