#!/bin/bash -e

BLUE='\E[1;34m'
GREEN='\E[1;32m'
RESET='\E[0m'

DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "${DIR}/.."

export BASE_TAG=latest
export OPENRESTY_VERSION=1.19.3.1
export LUA_VERSION=5.1.5
export LUAROCKS_VERSION=3.3.1
export OPENSSL_VERSION=1.1.1t

docker build \
	--pull \
	--no-cache \
	--build-arg BASE_TAG \
	--build-arg OPENRESTY_VERSION \
	--build-arg LUA_VERSION \
	--build-arg LUAROCKS_VERSION \
	--build-arg OPENSSL_VERSION \
	-t nginx-full:dev \
	-f docker/Dockerfile \
	.

echo -e "${BLUE}❯ ${GREEN}Build Complete${RESET}"
