#!/bin/sh

# Credit: https://github.com/jlesage/docker-baseimage/blob/master/helpers/sed-patch

usage() {
    echo "usage: $(basename "$0") [SED_OPT...] SED_EXPRESSION FILE
sed with a patch-like behavior.
This helper returns:
  - A success when running the sed expression SED_EXPRESSION results in changes
    applied to file FILE.
  - An error when running the sed expression SED_EXPRESSION results in no change
    to file FILE.
NOTE: sed option '-i' is already supplied by this script.
"
}

eval FILE=\${$#}

if [ "$#" -lt 2 ]; then
    echo "ERROR: Not enough arguments."
    exit 1
fi

sed -i.bak "$@"
RC="$?"
if [ "$RC" -eq 0 ]; then
    diff "$FILE" "$FILE".bak > /dev/null 2>&1
    case $? in
        0)
            # Files are the same.
            echo "ERROR: No modification applied to $FILE."
            RC=1
            ;;
        1)
            # Files differ.
            RC=0
            ;;
        *)
            ;;
    esac
fi

rm -f "$FILE".bak
exit $RC
