name: Build Docker images

on:
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  build_base_image:
    runs-on: ubuntu-latest
    name: Build ${{ matrix.arch }} base image
    strategy:
      matrix:
        arch: ["aarch64", "amd64"]

    steps:
      - name: Check out repository
        uses: actions/checkout@v4.1.7

      - name: Set build arguments
        run: |
          cat versions >> $GITHUB_ENV
          if [[ -z "${{ github.head_ref }}" ]] && [[ "${{ github.event_name }}" == "push" ]]; then
              echo "BUILD_ARGS=--docker-hub-check" >> $GITHUB_ENV;
          fi

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/${{ matrix.arch }}

      - name: Login to DockerHub
        if: env.BUILD_ARGS == '--docker-hub-check'
        uses: docker/login-action@v3.3.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: false
          tags: ${{ github.repository_owner }}/nginx-full:latest
          build-args: |
            OPENRESTY_VERSION=${{ env.OPENRESTY_VERSION }},\
            CROWDSEC_OPENRESTY_BOUNCER_VERSION="${{ env.CROWDSEC_OPENRESTY_BOUNCER_VERSION }},\
            LUA_VERSION=${{ env.LUA_VERSION }},\
            LUAROCKS_VERSION=${{ env.LUAROCKS_VERSION }}

